name: Branch authors

on:
  push:
  delete:

jobs:
  push:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v2
        with:
          # DB 代わりにするブランチ
          ref: main
          # 別のリポジトリを使う場合は Personal Access Token が必要
          # token: ${{ secrets.PAT }}

      - name: Pusher
        run: |
          if [ ! -d $DIRECTORY ]
          then
            mkdir -p $DIRECTORY
            echo $NAME >> $DIRECTORY/author
          fi
        env:
          NAME: ${{ github.event.pusher.name }}
          DIRECTORY: ${{ github.event.ref }}

      - name: Sender
        run: |
          if [ ! -d $DIRECTORY ]
          then
            mkdir -p $DIRECTORY
            echo $NAME >> $DIRECTORY/author
          fi
        env:
          NAME: ${{ github.event.sender.login }}
          DIRECTORY: ${{ github.event.ref }}

      - name: Count changes
        id: changes
        run: |
          git status
          git add -N . # 新規ファイルを含める
          echo "::set-output name=count::$(git diff --name-only | wc -l)"

      - name: Git commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Branch authors"
          git push
        if: steps.changes.outputs.count > 0

  delete:
    runs-on: ubuntu-20.04
    if: github.event_name == 'delete'
    
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v2
        with:
          # DB 代わりにするブランチ
          ref: main
          # 別のリポジトリを使う場合は Personal Access Token が必要
          # token: ${{ secrets.PAT }}

      - name: Delete
        run: |
          if [ -d $DIRECTORY ]
          then
            git rm -r $DIRECTORY
          fi
        env:
          DIRECTORY: refs/heads/${{ github.event.ref }}

      - name: Count changes
        id: changes
        run: |
          git status
          git add -N . # 新規ファイルを含める
          git diff --name-only
          git diff --name-only --diff-filter=D
          echo "::set-output name=count::$(git diff --name-only | wc -l)"

      - name: Git commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Branch authors"
          git push
        if: steps.changes.outputs.count > 0
