name: Branch authors

on:
  push:
  delete:

jobs:
  push:
    runs-on: ubuntu-20.04
    if: github.event_name == 'push'

    steps:
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v2
        with:
          # DB 代わりにするブランチ
          ref: main
          # 別のリポジトリを使う場合は Personal Access Token が必要
          # token: ${{ secrets.PAT }}

      - name: Config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Pusher
        run: |
          if [ ! -d $REF ]
          then
            mkdir -p $REF
            echo $NAME >> ${REF}/author
            git add .
            git commit -m "${REF} is pushed"
          fi
        env:
          REF: ${{ github.event.ref }}
          NAME: ${{ github.event.pusher.name }}

#       - name: Sender
#         run: |
#           if [ ! -d $REF ]
#           then
#             mkdir -p $REF
#             echo $NAME >> ${REF}/author
#           fi
#         env:
#           REF: ${{ github.event.ref }}
#           NAME: ${{ github.event.sender.login }}

      - name: Push
        run: git push

  delete:
    runs-on: ubuntu-20.04
    if: github.event_name == 'delete'
    
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - uses: actions/checkout@v2
        with:
          # DB 代わりにするブランチ
          ref: main
          # 別のリポジトリを使う場合は Personal Access Token が必要
          # token: ${{ secrets.PAT }}

      - name: Config
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Delete branch
        run: |
          if [ -d $REF ]
          then
            git rm -r $REF
            git commit -m "${REF} is deleted"
          fi
        env:
          REF: refs/heads/${{ github.event.ref }}
        if: github.event.ref_type == 'branch'

      - name: Delete tag
        run: |
          if [ -d $REF ]
          then
            git rm -r $REF
            git commit -m "${REF} is deleted"
          fi
        env:
          REF: refs/tags/${{ github.event.ref }}
        if: github.event.ref_type == 'tag'

      - name: Push
        run: git push
