name: Branch authors

on:
  push:

jobs:
  save:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
          # 別のリポジトリを使う場合は Personal Access Token が必要
          # token: ${{ secrets.PAT }}

      - name: Pusher
        run: |
          if [ -e $DIRECTORY ]
          then
            echo $NAME >> $DIRECTORY/author
          fi
        env:
          NAME: ${{ github.event.pusher.name }}
          DIRECTORY: ${{ github.event.ref }}

      - name: Sender
        run: |
          if [ -e $DIRECTORY ]
          then
            echo $NAME >> $DIRECTORY/author
          fi
        env:
          NAME: ${{ github.event.sender.login }}
          DIRECTORY: ${{ github.event.ref }}

      - name: Git commit & push
        run: |
          git status
          git add -N . # 新規ファイルを含める
          if ! git diff --exit-code --quiet
          then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "Branch authors"
            git push
          fi
